use_frameworks!

platform :ios, '9.0'

target 'EncryptLib_Example' do
  pod 'EncryptLib', :path => '../'

  target 'EncryptLib_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
